name: dailyhabit
description: A new Flutter project.

publish_to: 'none' 

version: 2.0.0+8

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.1.2
  path_provider: ^2.0.4
  sqflite: ^2.0.2
  fl_chart: ^0.69.0
  flutter_local_notifications: ^17.2.3
  shared_preferences: ^2.0.7
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^3.0.1
  timezone: ^0.9.4
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/empty-tasks.svg
    - assets/images/round_logo.png


